<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'email' => 'nhan123@gmail.com',
                'first_name' => '',
                'last_name' => '',
                'full_name' => 'Huynh Trong Nhan',
                'nickname' => 'Nhan Huynh',
                'image' => 'images/ROVFdXRPqc0McZ7swQ1AkPgq9UOJQVt3MnKGjpD9.jpg',
                'DOB' => '1990-01-01',
                'bio' => 'Hello, I am Nhan.',
                'followings_count' => 0,
                'likes_count' => 0,
                'website_url' => 'https://example.com',
                'facebook_url' => 'https://facebook.com/johndoe',
                'twitter_url' => 'https://twitter.com/johndoe',
                'instagram_url' => 'https://instagram.com/johndoe',
                'password' => bcrypt('password123'),
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'email' => 'tuan123@gmail.com',
                'first_name' => '',
                'last_name' => '',
                'full_name' => 'Nguyen Minh Tuan',
                'nickname' => 'Tuan Nguyen',
                'image' => 'images/ROVFdXRPqc0McZ7swQ1AkPgq9UOJQVt3MnKGjpD9.jpg',
                'DOB' => '2000-01-02',
                'bio' => 'Hello, I am Tuan.',   
                'followings_count' => 0,
                'likes_count' => 0,
                'website_url' => 'https://example.com',
                'facebook_url' => 'https://facebook.com/johndoe',
                'twitter_url' => 'https://twitter.com/johndoe',
                'instagram_url' => 'https://instagram.com/johndoe',
                'password' => bcrypt('password123'),
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'email' => 'quan123@gmail.com',
                'first_name' => '',
                'last_name' => '',
                'full_name' => 'Nguyễn Quang Quân',
                'nickname' => 'Quân Nguyễn',
                'image' => 'images/ROVFdXRPqc0McZ7swQ1AkPgq9UOJQVt3MnKGjpD9.jpg',
                'DOB' => '2004-02-02',
                'bio' => 'Hello, I am Quan.',
                'followings_count' => 0,
                'likes_count' => 0,
                'website_url' => 'https://example.com',
                'facebook_url' => 'https://facebook.com/johndoe',
                'twitter_url' => 'https://twitter.com/johndoe',
                'instagram_url' => 'https://instagram.com/johndoe',
                'password' => bcrypt('password123'),
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'email' => 'vy123@gmail.com',
                'first_name' => '',
                'last_name' => '',
                'full_name' => 'Trần Thanh Vy',
                'nickname' => 'Vy Trần',
                'image' => 'images/ROVFdXRPqc0McZ7swQ1AkPgq9UOJQVt3MnKGjpD9.jpg',
                'DOB' => '2003-01-01',
                'bio' => 'Hello, I am Vy.',
                'followings_count' => 0,
                'likes_count' => 0,
                'website_url' => 'https://example.com',
                'facebook_url' => 'https://facebook.com/johndoe',
                'twitter_url' => 'https://twitter.com/johndoe',
                'instagram_url' => 'https://instagram.com/johndoe',
                'password' => bcrypt('password123'),
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'email' => 'Tram123@gmail.com',
                'first_name' => '',
                'last_name' => '',
                'full_name' => 'Le Bich Tram',
                'nickname' => 'Tram Le',
                'image' => 'images/ROVFdXRPqc0McZ7swQ1AkPgq9UOJQVt3MnKGjpD9.jpg',
                'DOB' => '2005-10-10',
                'bio' => 'Hello, I am Tram.',
                'followings_count' => 0,
                'likes_count' => 0,
                'website_url' => 'https://example.com',
                'facebook_url' => 'https://facebook.com/johndoe',
                'twitter_url' => 'https://twitter.com/johndoe',
                'instagram_url' => 'https://instagram.com/johndoe',
                'password' => bcrypt('password123'),
                'email_verified_at' => now(),
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
